/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import control.ProdiControl;
import control.MahasiswaControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import entity.Prodi;
import entity.Mahasiswa;
import table.TableMahasiswa;
import dao.*;
/**
 *
 * @author tkg
 */
public class MahasiswaView extends javax.swing.JFrame {
    private ProdiControl pc;
    private MahasiswaControl mc;
    private ProdiDAO pDao;
    String action = null;
    List<Prodi> listProdi;
    /**
     * Creates new form MahasiswaView
     */
    public MahasiswaView() {
        initComponents();
        pc = new ProdiControl();
        mc = new MahasiswaControl();
        setComponent(false);
        setEditDeleteBtn(false);
        showMahasiswa();
        setProdiToDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mainPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblNPM = new javax.swing.JLabel();
        txtNPM = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        lblProdi = new javax.swing.JLabel();
        cmbProdi = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        btnMenuProdi = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(220, 220, 220));

        lblTitle.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(20, 20, 20));
        lblTitle.setText("Mahasiswa");

        btnAdd.setBackground(new java.awt.Color(240, 240, 240));
        btnAdd.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(40, 40, 40));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(240, 240, 240));
        btnEdit.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(40, 40, 40));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(240, 120, 100));
        btnDelete.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(40, 40, 40));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtSearch.setBackground(new java.awt.Color(240, 240, 240));
        txtSearch.setForeground(new java.awt.Color(40, 40, 40));

        btnSearch.setBackground(new java.awt.Color(240, 240, 240));
        btnSearch.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(40, 40, 40));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblNPM.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblNPM.setForeground(new java.awt.Color(60, 60, 60));
        lblNPM.setText("NPM");

        txtNPM.setBackground(new java.awt.Color(240, 240, 240));
        txtNPM.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        txtNPM.setForeground(new java.awt.Color(40, 40, 40));

        txtNama.setBackground(new java.awt.Color(240, 240, 240));
        txtNama.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(40, 40, 40));

        lblNama.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblNama.setForeground(new java.awt.Color(60, 60, 60));
        lblNama.setText("Nama");

        lblProdi.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblProdi.setForeground(new java.awt.Color(60, 60, 60));
        lblProdi.setText("Nama");

        cmbProdi.setBackground(new java.awt.Color(240, 240, 240));
        cmbProdi.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        cmbProdi.setForeground(new java.awt.Color(40, 40, 40));

        btnSave.setBackground(new java.awt.Color(200, 230, 255));
        btnSave.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(40, 40, 40));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(240, 240, 240));
        btnCancel.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(40, 40, 40));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tblMahasiswa.setBackground(new java.awt.Color(240, 240, 240));
        tblMahasiswa.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        tblMahasiswa.setForeground(new java.awt.Color(40, 40, 40));
        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMahasiswa.setGridColor(new java.awt.Color(180, 180, 180));
        tblMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMahasiswa);

        btnMenuProdi.setBackground(new java.awt.Color(220, 220, 220));
        btnMenuProdi.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        btnMenuProdi.setForeground(new java.awt.Color(120, 120, 120));
        btnMenuProdi.setText("Program Studi");
        btnMenuProdi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMenuProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(btnCancel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSave))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProdi)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit))
                                    .addComponent(lblNPM)
                                    .addComponent(lblNama))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addGap(76, 76, 76)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch))
                            .addComponent(txtNPM, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbProdi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnMenuProdi)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnMenuProdi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(lblNPM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        setComponent(true);
        clearText();
        action = "Tambah";    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setComponent(true);
        txtNPM.setEnabled(false); //supaya NPM tidak bisa diubah
        action = "Ubah";    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        switch (getAnswer) {
            case 0: //jika jawaban user adalah Yes
                // Isilah code di sini……
                String npm = mc.searchMahasiswa(txtNPM.getText());
                mc.deleteDataMahasiswa(npm);
                setComponent(false);
                setEditDeleteBtn(false);
                clearText();
                showMahasiswa();
            break;
            case 1: //jika jawaban user adalah No
                setComponent(true);
                setEditDeleteBtn(false);
            break;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // Ketika button cari diklik maka akan menonaktifkan component Input
        setComponent(false);
        TableMahasiswa listMhs = mc.showMahasiswa(txtSearch.getText());

        if (listMhs.getRowCount() == 0) {
            //Ketika data yang dicari tidak ditemukan
            setEditDeleteBtn(false);
            JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
        } else {
            //Ketika data yang dicari ditemukan
            setEditDeleteBtn(true);
            tblMahasiswa.setModel(listMhs);
            txtNPM.setText(listMhs.getValueAt(0, 0).toString());
            txtNama.setText(listMhs.getValueAt(0, 1).toString());
            String kode_prodi = listMhs.getValueAt(0, 2).toString();
            int indexProdi = 0;
            for (Prodi prodi : listProdi) {
                if (prodi.getKodeProdi().equals(kode_prodi)) {
                    indexProdi = listProdi.indexOf(prodi);
                }
            }
            cmbProdi.setSelectedIndex(indexProdi);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int selectedIndex = cmbProdi.getSelectedIndex();
        Prodi selectedProdi = listProdi.get(selectedIndex);

        Mahasiswa m = new Mahasiswa(txtNPM.getText(),txtNama.getText(),selectedProdi);

        if (action.equals("Tambah")) {
            mc.insertDataMahasiswa(m);
        } else {
            mc.updateDataMahasiswa(m);
        }

        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
        showMahasiswa();    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnMenuProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProdiActionPerformed
        ProdiView pv = new ProdiView();
        this.dispose();
        pv.setVisible(true);    }//GEN-LAST:event_btnMenuProdiActionPerformed

    private void tblMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMahasiswaMouseClicked
        int indexProdi = -1;
        setEditDeleteBtn(true);
        setComponent(false);

        int clickedRow = tblMahasiswa.getSelectedRow();
        TableModel tm = tblMahasiswa.getModel();

        txtNPM.setText(tm.getValueAt(clickedRow, 0).toString());
        txtNama.setText(tm.getValueAt(clickedRow, 1).toString());
        String kode_prodi = tm.getValueAt(clickedRow, 3).toString();
        for(Prodi prodi : listProdi) {
            if (prodi.getKodeProdi().equals(kode_prodi)) {
                indexProdi = listProdi.indexOf(prodi);
            }
        }
        cmbProdi.setSelectedIndex(indexProdi);    }//GEN-LAST:event_tblMahasiswaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MahasiswaView().setVisible(true);
            }
        });
    }
    
    public void setComponent(boolean value) {
        txtNPM.setEnabled(value);
        txtNama.setEnabled(value);
        cmbProdi.setEnabled(value);
        btnSave.setEnabled(value);
        btnCancel.setEnabled(value);
    }

    public void setEditDeleteBtn(boolean value) {
        btnEdit.setEnabled(value);
        btnDelete.setEnabled(value);
    }

    public void clearText() {
        txtNPM.setText("");
        txtNama.setText("");
        cmbProdi.setSelectedIndex(0);
        txtSearch.setText("");
    }
    
    public void showMahasiswa() {
        tblMahasiswa.setModel(mc.showMahasiswa(""));
    }
    
    public List<Prodi> showListProdi() {
        List<Prodi> dataProdi = pDao.showProdi();
        return dataProdi;
    }
    
    public void setProdiToDropdown() {
        listProdi = pc.showListProdi();
        for (int i = 0; i < listProdi.size(); i++) {
            cmbProdi.addItem(listProdi.get(i));
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMenuProdi;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<Prodi> cmbProdi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNPM;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblProdi;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtNPM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}